export const ILANLAR = [
  {
    id: 1,
    title: 'LAPSEKİ EMEK TATILDE DENIZE 80 METRE TRIPLEKS VILLA',
    description: 'This is the description for Ilan 1.',
    price: '500,000 TL',
    adresDetay: 'Bahçeşehir Mahallesi, 12. Sokak No:15',
    adresIl: 'Istanbul',
    adresIlce: 'Başakşehir',
    image: 'images/emlak-image.png',
  },
  {
    id: 2,
    title: 'CANAKKALE LAPSEKI DENIZE SIFIR TINYHOUSE PROJESI TAKSIT FIRSATI',
    description: 'This is the description for Ilan 2.',
    price: '750,000 TL',
    adresDetay: 'Atatürk Mahallesi, 5. Cadde No:25',
    adresIl: 'Ankara',
    adresIlce: 'Çankaya',
    image: 'images/emlak-image.png',
  },
  {
    id: 3,
    title: 'Ilan 3',
    description: 'This is the description for Ilan 3.',
    price: '1,200,000 TL',
    adresDetay: 'Konak Mahallesi, 8. Sokak No:45',
    adresIl: 'Izmir',
    adresIlce: 'Konak',
    image: 'images/emlak-image.png',
  },
  {
    id: 4,
    title: 'Ilan 4',
    description: 'This is the description for Ilan 4.',
    price: '400,000 TL',
    adresDetay: 'Kadıköy Mahallesi, 3. Cadde No:10',
    adresIl: 'Istanbul',
    adresIlce: 'Kadıköy',
    image: 'images/emlak-image.png',
  },
  {
    id: 5,
    title: 'Ilan 5',
    description: 'This is the description for Ilan 5.',
    price: '600,000 TL',
    adresDetay: 'Mevlana Mahallesi, 7. Sokak No:20',
    adresIl: 'Konya',
    adresIlce: 'Selçuklu',
    image: 'images/emlak-image.png',
  },
  {
    id: 6,
    title: 'Ilan 6',
    description: 'This is the description for Ilan 6.',
    price: '1,000,000 TL',
    adresDetay: 'Etiler Mahallesi, 4. Cadde No:35',
    adresIl: 'Istanbul',
    adresIlce: 'Beşiktaş',
    image: 'images/emlak-image.png',
  },
  {
    id: 7,
    title: 'Ilan 7',
    description: 'This is the description for Ilan 7.',
    price: '850,000 TL',
    adresDetay: 'Yenikent Mahallesi, 9. Sokak No:12',
    adresIl: 'Ankara',
    adresIlce: 'Etimesgut',
    image: 'images/emlak-image.png',
  },
  {
    id: 8,
    title: 'Ilan 8',
    description: 'This is the description for Ilan 8.',
    price: '450,000 TL',
    adresDetay: 'Mavişehir Mahallesi, 2. Cadde No:8',
    adresIl: 'Izmir',
    adresIlce: 'Karşıyaka',
    image: 'images/emlak-image.png',
  },
  {
    id: 9,
    title: 'Ilan 9',
    description: 'This is the description for Ilan 9.',
    price: '3,000,000 TL',
    adresDetay: 'Moda Mahallesi, 6. Sokak No:50',
    adresIl: 'Istanbul',
    adresIlce: 'Kadıköy',
    image: 'images/emlak-image.png',
  },
  {
    id: 10,
    title: 'Ilan 10',
    description: 'This is the description for Ilan 10.',
    price: '1,500,000 TL',
    adresDetay: 'Balgat Mahallesi, 1. Cadde No:15',
    adresIl: 'Ankara',
    adresIlce: 'Çankaya',
    image: 'images/emlak-image.png',
  },
  {
    id: 11,
    title: 'Ilan 11',
    description: 'This is the description for Ilan 11.',
    price: '700,000 TL',
    adresDetay: 'Alsancak Mahallesi, 5. Sokak No:18',
    adresIl: 'Izmir',
    adresIlce: 'Konak',
    image: 'images/emlak-image.png',
  },
  {
    id: 12,
    title: 'Ilan 12',
    description: 'This is the description for Ilan 12.',
    price: '900,000 TL',
    adresDetay: 'Mimar Sinan Mahallesi, 10. Cadde No:25',
    adresIl: 'Bursa',
    adresIlce: 'Nilüfer',
    image: 'images/emlak-image.png',
  },
  {
    id: 13,
    title: 'Ilan 13',
    description: 'This is the description for Ilan 13.',
    price: '1,800,000 TL',
    adresDetay: 'Küçükyalı Mahallesi, 7. Sokak No:40',
    adresIl: 'Istanbul',
    adresIlce: 'Maltepe',
    image: 'images/emlak-image.png',
  },
  {
    id: 14,
    title: 'Ilan 14',
    description: 'This is the description for Ilan 14.',
    price: '1,100,000 TL',
    adresDetay: 'Kızılay Mahallesi, 8. Cadde No:30',
    adresIl: 'Ankara',
    adresIlce: 'Çankaya',
    image: 'images/emlak-image.png',
  },
  {
    id: 15,
    title: 'Ilan 15',
    description: 'This is the description for Ilan 15.',
    price: '750,000 TL',
    adresDetay: 'Narlıdere Mahallesi, 3. Sokak No:22',
    adresIl: 'Izmir',
    adresIlce: 'Narlıdere',
    image: 'images/emlak-image.png',
  },
  {
    id: 16,
    title: 'Ilan 16',
    description: 'This is the description for Ilan 16.',
    price: '1,600,000 TL',
    adresDetay: 'Güzelbahçe Mahallesi, 12. Cadde No:55',
    adresIl: 'Izmir',
    adresIlce: 'Güzelbahçe',
    image: 'images/emlak-image.png',
  },
  {
    id: 17,
    title: 'Ilan 17',
    description: 'This is the description for Ilan 17.',
    price: '2,500,000 TL',
    adresDetay: 'Bebek Mahallesi, 5. Sokak No:88',
    adresIl: 'Istanbul',
    adresIlce: 'Beşiktaş',
    image: 'images/emlak-image.png',
  },
  {
    id: 18,
    title: 'Ilan 18',
    description: 'This is the description for Ilan 18.',
    price: '1,300,000 TL',
    adresDetay: 'Batıkent Mahallesi, 4. Cadde No:77',
    adresIl: 'Ankara',
    adresIlce: 'Yenimahalle',
    image: 'images/emlak-image.png',
  },
  {
    id: 19,
    title: 'Ilan 19',
    description: 'This is the description for Ilan 19.',
    price: '400,000 TL',
    adresDetay: 'Osmangazi Mahallesi, 1. Sokak No:5',
    adresIl: 'Bursa',
    adresIlce: 'Osmangazi',
    image: 'images/emlak-image.png',
  },
  {
    id: 20,
    title: 'Ilan 20',
    description: 'This is the description for Ilan 20.',
    price: '950,000 TL',
    adresDetay: 'Çamlıca Mahallesi, 2. Cadde No:12',
    adresIl: 'Istanbul',
    adresIlce: 'Üsküdar',
    image: 'images/emlak-image.png',
  },
];

