export const ILANLAR = [
  {
    id: 1,
    title: 'LAPSEKİ EMEK TATILDE DENIZE 80 METRE TRIPLEKS VILLA',
    description: 'This is the description for Ilan 1.',
    price: '500,000 TL',
    ilanTarihi: '2025-01-01',
    ilanNo: '123456',
    emlakTipi: 'Villa',
    m2Brut: 180,
    m2Net: 160,
    acikAlanM2: 20,
    odaSayisi: '3+1',
    binaYasi: 5,
    katSayisi: 3,
    isitma: 'Kombi',
    banyoSayisi: 2,
    mutfak: 'Açık Mutfak',
    balkon: true,
    esyali: false,
    kullanimDurumu: 'Boş',
    siteIcerisinde: true,
    siteAdi: 'Lapseki Tatil Sitesi',
    aidatTL: 150,
    krediyeUygun: true,
    tapuDurumu: 'Kat İrtifakı',
    kimden: 'Emlak Ofisinden',
    takas: false,
    adresDetay: 'Bahçeşehir Mahallesi, 12. Sokak No:15',
    adresIl: 'Istanbul',
    adresIlce: 'Başakşehir',
    image: 'images/ilan-image.png',
  },
  {
    id: 2,
    title: 'CANAKKALE LAPSEKI DENIZE SIFIR TINYHOUSE PROJESI TAKSIT FIRSATI',
    description: 'This is the description for Ilan 2.',
    price: '750,000 TL',
    ilanTarihi: '2025-01-02',
    ilanNo: '123457',
    emlakTipi: 'Tinyhouse',
    m2Brut: 50,
    m2Net: 45,
    acikAlanM2: 10,
    odaSayisi: '1+1',
    binaYasi: 1,
    katSayisi: 1,
    isitma: 'Şömine',
    banyoSayisi: 1,
    mutfak: 'Amerikan Mutfak',
    balkon: false,
    esyali: true,
    kullanimDurumu: 'Boş',
    siteIcerisinde: true,
    siteAdi: 'Deniz Tinyhouse Projesi',
    aidatTL: 50,
    krediyeUygun: true,
    tapuDurumu: 'Kat Mülkiyeti',
    kimden: 'İnşaat Firmasından',
    takas: false,
    adresDetay: 'Atatürk Mahallesi, 5. Cadde No:25',
    adresIl: 'Ankara',
    adresIlce: 'Çankaya',
    image: 'images/ilan-image.png',
  },
  {
    id: 3,
    title: 'Ilan 3',
    description: 'This is the description for Ilan 3.',
    price: '1,200,000 TL',
    ilanTarihi: '2025-01-03',
    ilanNo: '123458',
    emlakTipi: 'Daire',
    m2Brut: 150,
    m2Net: 130,
    acikAlanM2: 10,
    odaSayisi: '2+1',
    binaYasi: 10,
    katSayisi: 2,
    isitma: 'Merkezi',
    banyoSayisi: 1,
    mutfak: 'Kapalı Mutfak',
    balkon: true,
    esyali: false,
    kullanimDurumu: 'Kiracı Oturuyor',
    siteIcerisinde: false,
    siteAdi: '',
    aidatTL: 0,
    krediyeUygun: true,
    tapuDurumu: 'Kat Mülkiyeti',
    kimden: 'Sahibinden',
    takas: true,
    adresDetay: 'Konak Mahallesi, 8. Sokak No:45',
    adresIl: 'Izmir',
    adresIlce: 'Konak',
    image: 'images/ilan-image.png',
  },
  {
    id: 4,
    title: 'Kadıköy Merkezde Şık ve Modern Daire',
    description: 'Kadıköy\'de konforlu bir yaşam sunan modern bir daire.',
    price: '400,000 TL',
    ilanTarihi: '2025-01-04',
    ilanNo: '123459',
    emlakTipi: 'Daire',
    m2Brut: 120,
    m2Net: 100,
    acikAlanM2: 0,
    odaSayisi: '2+1',
    binaYasi: 5,
    katSayisi: 1,
    isitma: 'Doğalgaz',
    banyoSayisi: 1,
    mutfak: 'Kapalı Mutfak',
    balkon: true,
    esyali: false,
    kullanimDurumu: 'Boş',
    siteIcerisinde: false,
    siteAdi: '',
    aidatTL: 0,
    krediyeUygun: true,
    tapuDurumu: 'Kat Mülkiyeti',
    kimden: 'Sahibinden',
    takas: false,
    adresDetay: 'Kadıköy Mahallesi, 3. Cadde No:10',
    adresIl: 'Istanbul',
    adresIlce: 'Kadıköy',
    image: 'images/ilan-image.png',
  },
  {
    id: 5,
    title: 'Konya Selçuklu\'da Bahçeli Müstakil Ev',
    description: 'Konya\'da huzurlu bir yaşam sunan geniş bahçeli müstakil ev.',
    price: '600,000 TL',
    ilanTarihi: '2025-01-05',
    ilanNo: '123460',
    emlakTipi: 'Müstakil Ev',
    m2Brut: 200,
    m2Net: 180,
    acikAlanM2: 50,
    odaSayisi: '4+1',
    binaYasi: 3,
    katSayisi: 2,
    isitma: 'Kombi',
    banyoSayisi: 2,
    mutfak: 'Açık Mutfak',
    balkon: true,
    esyali: false,
    kullanimDurumu: 'Boş',
    siteIcerisinde: false,
    siteAdi: '',
    aidatTL: 0,
    krediyeUygun: true,
    tapuDurumu: 'Kat Mülkiyeti',
    kimden: 'Emlak Ofisinden',
    takas: false,
    adresDetay: 'Mevlana Mahallesi, 7. Sokak No:20',
    adresIl: 'Konya',
    adresIlce: 'Selçuklu',
    image: 'images/ilan-image.png',
  },
  {
    id: 6,
    title: 'Etiler\'de Lüks Rezidans Dairesi',
    description: 'Etiler\'de prestijli bir yaşam sunan lüks rezidans dairesi.',
    price: '1,000,000 TL',
    ilanTarihi: '2025-01-06',
    ilanNo: '123461',
    emlakTipi: 'Rezidans',
    m2Brut: 150,
    m2Net: 130,
    acikAlanM2: 10,
    odaSayisi: '3+1',
    binaYasi: 2,
    katSayisi: 10,
    isitma: 'Merkezi Sistem',
    banyoSayisi: 2,
    mutfak: 'Açık Mutfak',
    balkon: false,
    esyali: true,
    kullanimDurumu: 'Boş',
    siteIcerisinde: true,
    siteAdi: 'Etiler Rezidans',
    aidatTL: 500,
    krediyeUygun: true,
    tapuDurumu: 'Kat Mülkiyeti',
    kimden: 'Emlak Ofisinden',
    takas: false,
    adresDetay: 'Etiler Mahallesi, 4. Cadde No:35',
    adresIl: 'Istanbul',
    adresIlce: 'Beşiktaş',
    image: 'images/ilan-image.png',
  },
  {
    id: 7,
    title: 'Ankara Etimesgut\'ta Yeni Yapı Satılık Daire',
    description: 'Etimesgut\'ta merkezi konumda yeni yapılmış geniş daire.',
    price: '850,000 TL',
    ilanTarihi: '2025-01-07',
    ilanNo: '123462',
    emlakTipi: 'Daire',
    m2Brut: 140,
    m2Net: 120,
    acikAlanM2: 10,
    odaSayisi: '3+1',
    binaYasi: 1,
    katSayisi: 7,
    isitma: 'Doğalgaz',
    banyoSayisi: 2,
    mutfak: 'Kapalı Mutfak',
    balkon: true,
    esyali: false,
    kullanimDurumu: 'Boş',
    siteIcerisinde: true,
    siteAdi: 'Etimesgut Sitesi',
    aidatTL: 100,
    krediyeUygun: true,
    tapuDurumu: 'Kat Mülkiyeti',
    kimden: 'Emlak Ofisinden',
    takas: false,
    adresDetay: 'Yenikent Mahallesi, 9. Sokak No:12',
    adresIl: 'Ankara',
    adresIlce: 'Etimesgut',
    image: 'images/ilan-image.png',
  },
  {
    id: 8,
    title: 'Karşıyaka\'da Denize Yakın Şık Daire',
    description: 'Karşıyaka\'da merkezi konumda şık ve modern daire.',
    price: '450,000 TL',
    ilanTarihi: '2025-01-08',
    ilanNo: '123463',
    emlakTipi: 'Daire',
    m2Brut: 110,
    m2Net: 95,
    acikAlanM2: 5,
    odaSayisi: '2+1',
    binaYasi: 8,
    katSayisi: 5,
    isitma: 'Kombi',
    banyoSayisi: 1,
    mutfak: 'Kapalı Mutfak',
    balkon: true,
    esyali: false,
    kullanimDurumu: 'Kiracı Oturuyor',
    siteIcerisinde: false,
    siteAdi: '',
    aidatTL: 0,
    krediyeUygun: true,
    tapuDurumu: 'Kat İrtifakı',
    kimden: 'Sahibinden',
    takas: true,
    adresDetay: 'Mavişehir Mahallesi, 2. Cadde No:8',
    adresIl: 'Izmir',
    adresIlce: 'Karşıyaka',
    image: 'images/ilan-image.png',
  },
];

